<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LombaModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('c_lomba')->insert([
            
            [
               'kode_lomba' => 'LMB001',
                'nama_lomba' => 'UI/UX DESIGN COMPETITION',
                'id_tingkat_kompetisi' => 1,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-03',
                'tanggal_akhir_pendaftaran' => '2025-07-01',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://docs.google.com/forms/d/e/1FAIpQLSckXQgQL5CEKACsLLIPQ-tAOiQ1MwVFEU8DVzarvLKyLyLTkw/viewform',
                'deskripsi_lomba' => 'Lomba desain UI/UX untuk mahasiswa tingkat regional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/it-comfest-ui_ux.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB002',
                'nama_lomba' => 'IT Festival 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 2,
                'tanggal_mulai_pendaftaran' => '2025-05-20',
                'tanggal_akhir_pendaftaran' => '2025-06-18',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://ipb.link/form-pendaftaran-itfest',
                'deskripsi_lomba' => 'Kompetisi Capture The Flag untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/it_fest.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB003',
                'nama_lomba' => 'IT Festival 2026',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 2,
                'tanggal_mulai_pendaftaran' => '2025-05-20',
                'tanggal_akhir_pendaftaran' => '2025-06-18',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://ipb.link/form-pendaftaran-itfest',
                'deskripsi_lomba' => 'Kompetisi pengembangan perangkat lunak untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/it_fest.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB004',
                'nama_lomba' => 'UKM Cyber Design Competition 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-05-25',
                'tanggal_akhir_pendaftaran' => '2025-06-10',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://linktr.ee/ucdc2025',
                'deskripsi_lomba' => 'Kompetisi keamanan siber untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/ucdc.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB005',
                'nama_lomba' => 'NATIONAL COMPETITION SILOGY EXPO EDUCATION FAIR 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-19',
                'tanggal_akhir_pendaftaran' => '2025-06-21',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://linktr.ee/SilogyExpo',
                'deskripsi_lomba' => 'Kompetisi desain UI/UX untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/silogy.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB006',
                'nama_lomba' => 'NATIONAL COMPETITION SILOGY EXPO EDUCATION FAIR 2026',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-19',
                'tanggal_akhir_pendaftaran' => '2025-06-21',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://linktr.ee/SilogyExpo',
                'deskripsi_lomba' => 'Kompetisi pengembangan web untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/silogy.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB007',
                'nama_lomba' => 'Lomba Digital FESIFO 3.0',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-16',
                'tanggal_akhir_pendaftaran' => '2025-06-08',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://linktr.ee/FESIFO03',
                'deskripsi_lomba' => 'Kompetisi desain UI/UX untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/fesifo.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB008',
                'nama_lomba' => 'DATATHON 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-06-01',
                'tanggal_akhir_pendaftaran' => '2025-06-10',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://event.ristek.cs.ui.ac.id/datathon-registration',
                'deskripsi_lomba' => 'Kompetisi data science, machine learning, dan AI untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/datathon-ui.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB009',
                'nama_lomba' => 'SIEGA CUP 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-05-16',
                'tanggal_akhir_pendaftaran' => '2025-06-14',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'http://bit.ly/SIEGACUP2025',
                'deskripsi_lomba' => 'Kompetisi desain UI/UX untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/siega-cup.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB010',
                'nama_lomba' => 'INSPACE 2025: INSPACE COMPETITIONS',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-05-17',
                'tanggal_akhir_pendaftaran' => '2025-06-19',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://inspace.itk.ac.id/competition/BPC-2025',
                'deskripsi_lomba' => 'Kompetisi bisnis TIK untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/inspace.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB011',
                'nama_lomba' => 'WTO Secretariat, GTP & CropLife International Hackathon 2025',
                'id_tingkat_kompetisi' => 3,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-01',
                'tanggal_akhir_pendaftaran' => '2025-07-01',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://opportunitiesforyouth.org/2025/05/06/international-hackathon-2025/',
                'deskripsi_lomba' => 'Hackathon internasional untuk inovasi teknologi.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/wto-hackathon.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB012',
                'nama_lomba' => 'ITSEC: CTF Competition 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-01',
                'tanggal_akhir_pendaftaran' => '2025-07-31',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://itsecsummitregistration.com/registration',
                'deskripsi_lomba' => 'Kompetisi keamanan siber (Capture The Flag) untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/itsec-cs.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB013',
                'nama_lomba' => 'DigiNation Competition 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 1,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-02',
                'tanggal_akhir_pendaftaran' => '2025-06-06',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://s.id/digination-competition',
                'deskripsi_lomba' => 'Kompetisi kecerdasan buatan untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/digination.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB014',
                'nama_lomba' => 'TECHFEST COMPETITION 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-07',
                'tanggal_akhir_pendaftaran' => '2025-06-12',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://docs.google.com/forms/d/e/1FAIpQLSfLAZPOlMWgTWXzkArHo0zsTnGPChMS8vBITK8C4VmHUy8vGQ/viewform',
                'deskripsi_lomba' => 'Kompetisi data science untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/techfest.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB015',
                'nama_lomba' => 'UI/UX Mobile Design Competition',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-01',
                'tanggal_akhir_pendaftaran' => '2025-07-10',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://docs.google.com/forms/d/e/1FAIpQLSfuUmuHcT5a2ZAm3gBk6Hidncwy_3eKL5FDKYA1kpw45ukDWw/viewform',
                'deskripsi_lomba' => 'Kompetisi desain UI/UX mobile untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/euformatika.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB016',
                'nama_lomba' => 'Web programming competition 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-05-25',
                'tanggal_akhir_pendaftaran' => '2025-06-22',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://hmtifunissula.com/event',
                'deskripsi_lomba' => 'Kompetisi pengembangan web untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/informatics-event-webdev.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB017',
                'nama_lomba' => 'Garuda Hacks 6.0',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 1,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 4,
                'tanggal_mulai_pendaftaran' => '2025-07-24',
                'tanggal_akhir_pendaftaran' => '2025-07-26',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://garudahacks.com/',
                'deskripsi_lomba' => 'Kompetisi pemrograman untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/garuda-hacks.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB018',
                'nama_lomba' => 'PEKAN IT 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 2,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-01',
                'tanggal_akhir_pendaftaran' => '2025-06-30',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://himtika.cs.unsika.ac.id/pekan-it/competitive.html#',
                'deskripsi_lomba' => 'Kompetisi pemrograman untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/pekan-it.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB019',
                'nama_lomba' => 'EcoVation',
                'id_tingkat_kompetisi' => 3,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-06-05',
                'tanggal_akhir_pendaftaran' => '2025-06-17',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://ecovation.dwdgbinus.com/',
                'deskripsi_lomba' => 'Kompetisi bisnis TIK untuk tingkat internasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/ecovation.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB020',
                'nama_lomba' => 'B-STARTION X by.U 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 1,
                'id_biaya_pendaftaran' => 1,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-27',
                'tanggal_akhir_pendaftaran' => '2025-07-06',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://linktr.ee/bstar25',
                'deskripsi_lomba' => 'Kompetisi bisnis TIK untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/bcc-byu.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB021',
                'nama_lomba' => 'GAMESEED 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 3,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-05-23',
                'tanggal_akhir_pendaftaran' => '2025-07-11',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'http://tally.so/r/mYyVKv',
                'deskripsi_lomba' => 'Kompetisi pengembangan game untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/gameseed.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB022',
                'nama_lomba' => 'FIT COMPETITION 2025 DATA SCIENCE',
                'id_tingkat_kompetisi' => 3,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-04-21',
                'tanggal_akhir_pendaftaran' => '2025-06-21',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://fti.uksw.edu/fit2025/category-data.html',
                'deskripsi_lomba' => 'Kompetisi data science untuk tingkat internasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/fit-ds.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB023',
                'nama_lomba' => 'Hackathon STEM 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 4,
                'tanggal_mulai_pendaftaran' => '2025-10-01',
                'tanggal_akhir_pendaftaran' => '2025-10-03',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://kompetisi.stem.or.id/hackathon/',
                'deskripsi_lomba' => 'Hackathon untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/stem.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB024',
                'nama_lomba' => 'BI-OJK Hackathon 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 1,
                'tanggal_mulai_pendaftaran' => '2025-06-05',
                'tanggal_akhir_pendaftaran' => '2025-07-11',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://hackathon.fekdi.co.id/#problem-statements',
                'deskripsi_lomba' => 'Hackathon untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/bi-ojk-hackathon.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB025',
                'nama_lomba' => 'International LegalTech Competition 2025: Prompting Challenge',
                'id_tingkat_kompetisi' => 3,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 9,
                'tanggal_mulai_pendaftaran' => '2025-01-01',
                'tanggal_akhir_pendaftaran' => '2025-08-31',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://www.fbe.org/international-legaltech-competition-2025-prompting-challenge/',
                'deskripsi_lomba' => 'Kompetisi kecerdasan buatan untuk tingkat internasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/iltc.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB026',
                'nama_lomba' => 'MAGE 11',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-02',
                'tanggal_akhir_pendaftaran' => '2025-07-28',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://mage-its.id/competition-detail/gamedev',
                'deskripsi_lomba' => 'Kompetisi pengembangan game untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/mage-gd.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB027',
                'nama_lomba' => 'FIT COMPETITION 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-04-21',
                'tanggal_akhir_pendaftaran' => '2025-06-21',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://fti.uksw.edu/fit2025/category-cyber.html',
                'deskripsi_lomba' => 'Kompetisi keamanan siber untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/fit-cs.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB028',
                'nama_lomba' => 'FIT COMPETITION 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-04-21',
                'tanggal_akhir_pendaftaran' => '2025-06-21',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://fti.uksw.edu/fit2025/category.html',
                'deskripsi_lomba' => 'Kompetisi pengembangan web untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/fit-webdev.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB029',
                'nama_lomba' => 'FIT COMPETITION 2025',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-04-21',
                'tanggal_akhir_pendaftaran' => '2025-06-21',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://fti.uksw.edu/fit2025/category-mobile.html',
                'deskripsi_lomba' => 'Kompetisi pengembangan aplikasi mobile untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/fit-mobile.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB030',
                'nama_lomba' => 'MAGE 11',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-02',
                'tanggal_akhir_pendaftaran' => '2025-07-28',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://mage-its.id/sideCompeRegist/compeProg',
                'deskripsi_lomba' => 'Kompetisi pemrograman untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/mage-cp.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_lomba' => 'LMB031',
                'nama_lomba' => 'MAGE 11',
                'id_tingkat_kompetisi' => 2,
                'id_penyelenggara' => 2,
                'id_biaya_pendaftaran' => 3,
                'id_hadiah' => 3,
                'tanggal_mulai_pendaftaran' => '2025-06-02',
                'tanggal_akhir_pendaftaran' => '2025-07-28',
                'lokasi_lomba' => 'Online',
                'link_pendaftaran' => 'https://mage-its.id/sideCompeRegist/uiux',
                'deskripsi_lomba' => 'Kompetisi desain UI/UX untuk tingkat nasional.',
                'status_lomba' => 'Masih Berlangsung',
                'status_verifikasi' => 'Diverifikasi',
                'gambar_lomba' => 'storage/app/public/lomba/mage-ui_ux.jpg',
                'catatan' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
     ]);
    }
}