<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrestasiModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id_mahasiswa' => 1,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Hackathon Nasional Mahasiswa',
                'posisi' => 'Ketua',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 1',
                'jenis_prestasi' => 'Sains',
                'lokasi_kompetisi' => 'Universitas Indonesia',
                'tanggal_surat_tugas' => '2025-03-01',
                'tanggal_kompetisi' => '2025-03-10',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 20,
                'nomor_sertifikat' => 'CERT-HACK01',
                'foto_sertifikat' => 'hackathon.jpg',
                'link_perlombaan' => 'https://example.com/hackathon',
                'status' => 'Sudah Diverifikasi',
                'skor' => 70,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 1,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Kompetisi Robotika Perguruan Tinggi',
                'posisi' => 'Anggota',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 2',
                'jenis_prestasi' => 'Sains',
                'lokasi_kompetisi' => 'ITS Surabaya',
                'tanggal_surat_tugas' => '2025-01-15',
                'tanggal_kompetisi' => '2025-01-25',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 15,
                'nomor_sertifikat' => 'CERT-ROBO02',
                'foto_sertifikat' => 'robotika.jpg',
                'link_perlombaan' => 'https://example.com/robotika',
                'status' => 'Sudah Diverifikasi',
                'skor' => 50,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 2,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Turnamen E-Sport Nasional Kemendikbud',
                'posisi' => 'Anggota',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 3',
                'jenis_prestasi' => 'Olahraga',
                'lokasi_kompetisi' => 'Kementerian Pendidikan',
                'tanggal_surat_tugas' => '2025-02-10',
                'tanggal_kompetisi' => '2025-02-20',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 30,
                'nomor_sertifikat' => 'CERT-ESPORT03',
                'foto_sertifikat' => 'esport.jpg',
                'link_perlombaan' => 'https://example.com/esport',
                'status' => 'Sudah Diverifikasi',
                'skor' => 30,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 2,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Pekan Olahraga Mahasiswa Nasional (POMNAS)',
                'posisi' => 'Ketua',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 1',
                'jenis_prestasi' => 'Olahraga',
                'lokasi_kompetisi' => 'Universitas Negeri Malang',
                'tanggal_surat_tugas' => '2025-04-01',
                'tanggal_kompetisi' => '2025-04-15',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 40,
                'nomor_sertifikat' => 'CERT-POMNAS04',
                'foto_sertifikat' => 'pomnas.jpg',
                'link_perlombaan' => 'https://example.com/pomnas',
                'status' => 'Sudah Diverifikasi',
                'skor' => 70,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 3,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Lomba Catur Mahasiswa Tingkat Universitas',
                'posisi' => 'Anggota',
                'tingkat_kompetisi' => 'Regional',
                'juara_kompetisi' => 'Juara 2',
                'jenis_prestasi' => 'Olahraga',
                'lokasi_kompetisi' => 'Universitas Brawijaya',
                'tanggal_surat_tugas' => '2025-03-10',
                'tanggal_kompetisi' => '2025-03-20',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 12,
                'nomor_sertifikat' => 'CERT-CATUR05',
                'foto_sertifikat' => 'catur.jpg',
                'link_perlombaan' => 'https://example.com/catur',
                'status' => 'Sudah Diverifikasi',
                'skor' => 30,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 1,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Kompetisi Programming Kementerian Kominfo',
                'posisi' => 'Anggota',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 1',
                'jenis_prestasi' => 'Sains',
                'lokasi_kompetisi' => 'Kementerian Kominfo',
                'tanggal_surat_tugas' => '2025-05-01',
                'tanggal_kompetisi' => '2025-05-10',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 25,
                'nomor_sertifikat' => 'CERT-PROG06',
                'foto_sertifikat' => 'programming.jpg',
                'link_perlombaan' => 'https://example.com/programming',
                'status' => 'Belum Diverifikasi',
                'skor' => null,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 2,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Lomba UI/UX Design Kemenristek',
                'posisi' => 'Ketua',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 2',
                'jenis_prestasi' => 'Sains',
                'lokasi_kompetisi' => 'Kementerian Ristek',
                'tanggal_surat_tugas' => '2025-02-01',
                'tanggal_kompetisi' => '2025-02-10',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 18,
                'nomor_sertifikat' => 'CERT-UIUX07',
                'foto_sertifikat' => 'uiux.jpg',
                'link_perlombaan' => 'https://example.com/uiux',
                'status' => 'Belum Diverifikasi',
                'skor' => null,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 3,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Lomba IT Mahasiswa Tingkat Nasional',
                'posisi' => 'Anggota',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 3',
                'jenis_prestasi' => 'Sains',
                'lokasi_kompetisi' => 'Universitas Gadjah Mada',
                'tanggal_surat_tugas' => '2025-04-01',
                'tanggal_kompetisi' => '2025-04-12',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 22,
                'nomor_sertifikat' => 'CERT-IT08',
                'foto_sertifikat' => 'itmahasiswa.jpg',
                'link_perlombaan' => 'https://example.com/itmahasiswa',
                'status' => 'Belum Diverifikasi',
                'skor' => null,
                'catatan' => null,
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 2,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Olimpiade Sains Mahasiswa (OSM)',
                'posisi' => 'Anggota',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 1',
                'jenis_prestasi' => 'Sains',
                'lokasi_kompetisi' => 'Institut Teknologi Bandung',
                'tanggal_surat_tugas' => '2025-03-01',
                'tanggal_kompetisi' => '2025-03-08',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 28,
                'nomor_sertifikat' => 'CERT-OSM09',
                'foto_sertifikat' => 'osm.jpg',
                'link_perlombaan' => 'https://example.com/osm',
                'status' => 'Ditolak',
                'skor' => null,
                'catatan' => 'Sertifikat tidak sesuai format yang diminta.',
                'tanggal_pengajuan' => now(),
            ],
            [
                'id_mahasiswa' => 3,
                'id_prodi' => 1,
                'nama_kompetisi' => 'Kejuaraan Futsal Mahasiswa se-Indonesia',
                'posisi' => 'Ketua',
                'tingkat_kompetisi' => 'Nasional',
                'juara_kompetisi' => 'Juara 2',
                'jenis_prestasi' => 'Olahraga',
                'lokasi_kompetisi' => 'Universitas Negeri Yogyakarta',
                'tanggal_surat_tugas' => '2025-01-20',
                'tanggal_kompetisi' => '2025-01-30',
                'id_dosen' => 1,
                'id_periode' => 1,
                'jumlah_univ' => 35,
                'nomor_sertifikat' => 'CERT-FUTSAL10',
                'foto_sertifikat' => 'futsal.jpg',
                'link_perlombaan' => 'https://example.com/futsal',
                'status' => 'Ditolak',
                'skor' => null,
                'catatan' => 'Nama peserta tidak tercantum di sertifikat.',
                'tanggal_pengajuan' => now(),
            ],

        ];
        DB::table('prestasi')->insert($data);

    }
}
